<p>Start with data and importing libraries. 2 libraries we'll require are numpy and scikit-learn. </p>
<p>If you haven't installed them, you can install them in jupyter notebook itself :</p>
<em><b>!pip install numpy scikit-learn</b></em>

In [1]:
import numpy as np
X_data = np.array([[173, 182, 165, 154, 170]])
X_data = X_data.reshape((5,1))
y_data = np.array([68, 79, 65, 57, 64])

In [2]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_data, y_data)
model.predict([[176]])

array([71.90721649])

Now let us start with Mean Squared Error

In [3]:
y_pred = model.predict(X_data)

In [4]:
y_pred

array([69.69587629, 76.32989691, 63.79896907, 55.69072165, 67.48453608])

In [5]:
sse = (y_data - y_pred)**2

In [6]:
sse

array([ 2.87599639,  7.12945053,  1.44247529,  1.7142098 , 12.14199171])

In [7]:
mse = np.mean(sse)

In [8]:
mse

np.float64(5.060824742268041)

In [9]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_data, y_pred)

5.060824742268041