In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Classification

In [3]:
data = np.random.randn (10)
y = np.where (data<0, 0, 1)

In [4]:
data

array([-0.61722947,  0.94186388,  1.88298521,  0.04628778,  1.22814119,
       -1.84893573, -0.86909299, -1.19467838,  0.4392518 ,  1.55689511])

In [5]:
y

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [6]:
def sigmoid (z):
    return (1 / (1 + np.exp (-z)))

predicted_value = [sigmoid (i) for i in data]
predicted_value = np.array (predicted_value)

In [7]:
predicted_value

array([0.35041183, 0.719476  , 0.86795364, 0.51156988, 0.77349307,
       0.1359979 , 0.29544307, 0.23242326, 0.60808073, 0.82590737])

In [8]:
def logLoss (y_pred, y_true):
    return -(y_true * np.log (y_pred) + (1-y_true) * np.log (1-y_pred)).mean ()

In [9]:
loss = logLoss (predicted_value, y)

In [10]:
loss

0.32789787416505395

In [11]:
from sklearn.metrics import log_loss
log_loss(y_true=y, y_pred=predicted_value)

0.32789787416505395

In [12]:
import torch

In [13]:
from torch.nn import BCELoss

torchOutput = torch.Tensor (predicted_value)
torch_y = torch.Tensor (y)

torchLoss = BCELoss ()
torch_output = torchLoss (torchOutput, torch_y)
torch_output

tensor(0.3279)

In [14]:
from tensorflow.keras.losses import BinaryCrossentropy
bcetf = BinaryCrossentropy ()
tf_val = bcetf (y_true=y, y_pred=predicted_value)

In [15]:
tf_val

<tf.Tensor: shape=(), dtype=float32, numpy=0.32789788>